title: FIM (Web) - wp-config.php (/wp-config.php)
id: f5117dd2-509d-5222-a2f1-7dd91bfde509
status: experimental
description: >
  Integrity change under the web application tree (wp-config.php: /wp-config.php). Watch for webshell drops in upload dirs and tampering of core app files.
references:
  - https://attack.mitre.org/techniques/T1565/001/
author: DeusWatch (generated)
level: high
logsource:
  product: linux
  category: file_event
detection:
  selection:
    file.path|contains:
      - '/wp-config.php'
  change:
    event.action:
      - file_modified
      - file_deleted
  condition: selection and change
tags:
  - attack.t1565.001
  - attack.persistence
