title: FIM - netplan config (/etc/netplan/)
id: a50b1eee-ee57-5af0-a076-c5cc3c4c5078
status: experimental
description: >
  Integrity change on netplan config (/etc/netplan/). Modification/creation/deletion here often indicates tampering, backdooring, or track-covering.
references:
  - https://attack.mitre.org/techniques/T1565/001/
author: DeusWatch (generated)
level: medium
logsource:
  product: linux
  category: file_event
detection:
  selection:
    file.path|contains:
      - '/etc/netplan/'
  change:
    event.action:
      - file_modified
      - file_deleted
  condition: selection and change
tags:
  - attack.t1565.001
  - attack.impact
