ALTER TABLE events DROP COLUMN IF EXISTS http_host;
ALTER TABLE events DROP COLUMN IF EXISTS http_status;
ALTER TABLE events DROP COLUMN IF EXISTS http_uri;
ALTER TABLE events DROP COLUMN IF EXISTS http_method;
